### ISSUE TITLE
Criar os diagramas baseados nos requisitos

### ISSUE THREAD

**Issue by vgeruso** [manaboard/docs#2]
Criar os diagramas basicos para melhor visualização dos fluxoa básicos do sistema

## Todo

- [x] Diagrama de fluxo login
- [x] Diagrama de fluxo signup
- [x] Diagrama de fluxo create project
- [ ] Diagrama ER banco de dados
